# Generated by Django 6.1 on 2026-09-05 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='post_path',
            new_name='poster_path',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie_id')},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'movie_id')},
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie_poster',
        ),
    ]
