# Generated by Django 6.1 on 2026-09-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_post_path_favorite_poster_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
