# Generated by Django 6.1 on 2026-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favorite_rating_watchlist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='release_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='release_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
